# alias sai='sudo apt install'
# alias sau='sudo apt update && sudo apt upgrade'
# alias sap='sudo apt purge'
#alias as='apt show'
#alias sarc='sudo apt autoremove && sudo apt autoclean'

alias open='thunar ./'
alias sctl='systemctl'
alias jctl='journalctl'
alias jpnb='jupyter-notebook --browser=firefox'
alias sudo='sudo '

# Changing "ls" to "exa --git"
# alias ls='exa --color=always --group-directories-first'
# alias ll='ls -al' # The obvious answer.
# alias l='ll -h'
alias lg='ls -al --git' # git listing
alias lln='exa -al --group-directories-first | grep --color=always "\-> /home/skye/"' #view symlinks


alias curl='curl '
alias cat='bat '
